version: '3'

services:
  backend:
    build: .
    stdin_open: true
    tty: true
    working_dir: /home/application
    command: python -m flask run --port 5000 --host=0.0.0.0
    environment:
      - FLASK_APP=application.py
    env_file:
      - docker-env/be.env
    ports:
      - 5000:5000
    volumes:
      - .:/home/application
