version: '3'

services:
  backend:
    build: backend
    stdin_open: true
    tty: true
    working_dir: /home/backend
    command: python -m flask run --port 5000 --host=0.0.0.0
    environment:
      - FLASK_APP=application.py
    env_file:
      - docker-env/be.env
    ports:
      - 5000:5000
    volumes:
      - ./docker-data:/home/docker-data
      - ./backend:/home/backend

  frontend:
    build: frontend
    working_dir: /home/frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/home/frontend
      - /home/frontend/node_modules
